version: '3.2'

version: '3.2'

networks: 
  a_network:
    driver: bridge

services:

  client:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - a_network

  nginx:
    image: nginx:alpine
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    command: [nginx, '-g', 'daemon off;']
    networks:
      - a_network
